trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    pip install -r environment/conda.yml
  displayName: 'Install dependencies'

- script: |
    python scripts/train.py
  displayName: 'Train and register model'

- script: |
    python deployment/deploy.py
  displayName: 'Deploy model to endpoint'
