trigger:
  branches:
    include:
      - main

stages:
- stage: Dev
  jobs:
  - job: TrainAndRegister
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        pip install -r environment/conda.yml
      displayName: 'Install dependencies'
    - script: |
        python scripts/train.py
      displayName: 'Train model'
    - script: |
        python register_model.py
      displayName: 'Register model'

- stage: Prod
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - job: CreateScoringImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python create_scoring_image.py
      displayName: 'Create Docker scoring image'
