trigger:
  branches:
    include:
      - main

variables:
  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  AZURE_RESOURCE_GROUP: $(AZURE_RESOURCE_GROUP)
  AZURE_WORKSPACE_NAME: $(AZURE_WORKSPACE_NAME)

stages:
- stage: Dev
  jobs:
  - job: TrainAndRegister
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        pip install -r requirements.txt
      displayName: 'Install dependencies with pip'
    - script: |
        python scripts/train.py
      displayName: 'Train model'
    - script: |
        python register_model.py
      displayName: 'Register model'

- stage: Prod
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: DeployToAKS
    environment: aks-prod  # this will enable manual approval in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - script: |
              pip install -r requirements.txt
            displayName: 'Install dependencies'
          - script: |
              python deploy_to_aks.py
            displayName: 'Deploy model to AKS'
