trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Your Azure Subscription Name'
  azureResourceGroup: 'mlops-rg'
  azureWorkspace: 'mlops-workspace'

stages:
- stage: CI
  jobs:
  - job: BuildAndTrain
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - script: |
        pip install -r ci/requirements.txt
        python ci/create_workspace.py
        python ci/train.py
        python ci/model_eval.py
        python ci/register_model.py
      displayName: 'Train and Register Model'

- stage: CD
  dependsOn: CI
  jobs:
  - job: DeployModel
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - script: |
        pip install -r cd/requirements.txt
        python cd/deploy.py
      displayName: 'Deploy Registered Model'
