trigger:
  branches:
    include:
      - main

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: TrainAndRegister
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - script: |
              pip install -r ci/requirements.txt
              python ci/create_workspace.py
              python ci/train.py
              python ci/model_eval.py
              python ci/register_model.py
              pytest ci/tests
            displayName: 'Run CI steps'

  - stage: CD
    displayName: "Continuous Deployment"
    dependsOn: CI
    condition: succeeded()
    jobs:
      - job: DeployModel
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - script: |
              pip install -r cd/requirements.txt
              python cd/deploy.py
            displayName: 'Run CD deployment'
