trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CI
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      pip install -r ci/requirements.txt
      python ci/train.py
      python ci/model_eval.py
      python ci/register_model.py

- job: CD
  dependsOn: CI
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      pip install -r cd/requirements.txt
      bash cd/run_pipeline.sh
