trigger:
  branches:
    include:
      - main

variables:
  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  AZURE_RESOURCE_GROUP: mlopstest1
  AZURE_WORKSPACE_NAME: mlopstest1
  AZURE_LOCATION: westus2

stages:
- stage: Dev
  displayName: "Train and Register Model"
  jobs:
  - job: TrainRegister
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        bash install_requirements.sh
      displayName: "Install All Requirements"
    - script: |
        python scripts/train.py
      workingDirectory: dev
      displayName: "Train Model"
    - script: |
        python scripts/register_model.py
      workingDirectory: dev
      displayName: "Register Model"

- stage: Prod
  displayName: "Deploy to Endpoint"
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        bash install_requirements.sh
      displayName: "Install All Requirements"
    - script: |
        python scripts/deploy_endpoint.py
      workingDirectory: prod
      displayName: "Deploy to Azure ML ACI Endpoint"
